module.exports = {
  CANDIDATE_MINIMAL_PRICE: process.env.CANDIDATE_MINIMAL_PRICE,
  AUCTIONEER_CUT: 10000,
  AUCTIONEER_MINTING_CUT: 7000,
  LOG: process.env.LOG,
  INFURA_KEY: process.env.INFURA_KEY,
  WALLET_MNEMONIC: process.env.WALLET_MNEMONIC,
  WALLET_PASSWORDS: process.env.WALLET_PASSWORDS
};
