module.exports = {
  LOG: process.env.LOG,
  INFURA_KEY: process.env.INFURA_KEY,
  WALLET_MNEMONIC: process.env.WALLET_MNEMONIC,
  WALLET_PASSWORDS: process.env.WALLET_PASSWORDS,
  MARBLE_FACTORY_CONTRACT_ADDRESS: process.env.MARBLE_FACTORY_CONTRACT_ADDRESS,
  MARBLE_METATRANSACTIONS_CHAIN: process.env.MARBLE_METATRANSACTIONS_CHAIN,
};
